{{- $releaseName := .Release.Name -}}
{{- $chartName := include "locust-server-boilerplate.name" . -}}
{{- $cloudProviderFlavor := include "locust-server-boilerplate.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "locust-server-boilerplate.environment" . }}
    release: {{ $releaseName }}
    {{- include "locust-server-boilerplate.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "locust-server-boilerplate.selectorLabels" . | nindent 4 }}
{{- end }}