{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/rewrite: "ServiceName={{ template "map-proxy.fullname" . }}-map-proxy rewrite=/"
    nginx.org/location-snippets: |
      proxy_set_header 'X-Script-Name' '{{ .Values.ingress.mapProxyPath }}';
    nginx.org/mergeable-ingress-type: "minion"
    #nginx.org/redirect-to-https: "True" #dont work in minion, should be set in master
    #nginx.org/hsts-behind-proxy: "True" #dont work in minion or master despite documentation
  name: {{ template "locust.fullname" . }}-ingress
spec:
  rules:
    - host: {{quote .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "map-proxy.fullname" . }}-nginx
                port:
                  number: {{ .Values.ports.mapProxy.port }}
            path: {{ .Values.ingress.mapProxyPath }}(/|$)(.*)
            pathType: Prefix
{{- end }}