on:
  push:
    tags:
      - "v*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/Libot-Mipui-Org/automation-locust
          azure-pipeline-name: "build-and-push-ACR"
          azure-devops-token: ${{ secrets.AZURE_TOKEN_NEW }}
